### ISSUE TITLE
pm2 启动日志报错

### ISSUE THREAD

**Issue by usergyt** [87789771/meimei-nestjs-admin#10]
我这里用pm2启动 日志报错,  node 能启动

0|main  | [Nest] 14193  - 11/02/2022, 10:35:47 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
0|main  | MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "aurora-mysql", "aurora-postgres", "better-sqlite3", "capacitor", "cockroachdb", "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "nativescript", "oracle", "postgres", "react-native", "sap", "sqlite", "sqljs", "spanner".
 
是什么原因导致的呢 ，帮看下谢谢🙏

**Comment by 87789771** [comment]
你这一看就是数据库没连接上， 你肯定是启动命令用的不对。你查看你应该启动开发环境还是生成环境，然后对应启动相应的命令。

**Comment by usergyt** [comment]
我是 yarn run start:prod  打包dist文件， 然后 pm2 start ./dist/main.js  
是这样的吗？

**Comment by 87789771** [comment]
在项目根目录下 直接    pm2  start npm --start              还可以添加 --watch --name 按你需要添加

**Comment by 87789771** [comment]
在项目根目录下 直接    pm2  start npm --start              还可以添加 --watch --name 按你需要添加

**Comment by usergyt** [comment]
可以了 谢谢
