### ISSUE TITLE
Upload avatar error in personalCenter

### ISSUE THREAD

**Issue by zhanggoodzhi** [87789771/meimei-nestjs-admin#3]
the avatar interface upload a blob file to backend , the "file.originalname" in upload.module.ts has no suffix.

**Comment by 87789771** [comment]
哥们请说中文，这个我没考虑过，我考虑的都是 file 类型，可以解析到上传文件的后缀， 你上传的 blob可能解析不到。  欢迎你进行更改。 这个项目也是我学习nest时写的，作为一个前端，好多地方可能考虑的不太全面。

**Comment by 87789771** [comment]
已经理解你的我问题了。  由于解析不到文件后缀 导致 请求上传后的文件的时候找不到文件， 比如头像上传的时候 文件名就没有后缀。 目前问题已经解决。
