### ISSUE TITLE
数据sql中没有初始数据

### ISSUE THREAD

**Issue by weips001** [87789771/meimei-nestjs-admin#33]
有没有初始数据可以给一份

**Comment by 87789771** [comment]
后端代码根目录下有。

**Comment by weips001** [comment]
那边只有创建表的，没有具体的数据 prisma这个项目

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月06日 14:49 |
| 收件人 | 87789771/meimei-nestjs-admin ***@***.***> |
| 抄送人 | weips ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [87789771/meimei-nestjs-admin] 数据sql中没有初始数据 (Issue #33) |

后端代码根目录下有。

**Comment by weips001** [comment]
啊 不好意思，是我把表名弄错了 一直没成功

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月06日 14:49 |
| 收件人 | 87789771/meimei-nestjs-admin ***@***.***> |
| 抄送人 | weips ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [87789771/meimei-nestjs-admin] 数据sql中没有初始数据 (Issue #33) |

后端代码根目录下有。
