### ISSUE TITLE
账号状态冲突

### ISSUE THREAD

**Issue by ljnMeow** [87789771/meimei-nestjs-admin#38]
作者您好，我发现一个不知道算不算 bug 的地方，假如我登录了 admin 账号，然后又新开一个浏览器再登录 admin 账号，他们两个是可以同时操作的，这没问题，但是我其中一个点退出登录后，另外一个的 token 也失效了

这种情况就有点奇怪，因为不是单点登录，所以账号的状态应该是独立的（就算是同一个账号），单点登录才会出现顶号操作

这样就会造成我电脑登录 admin，然后别人也在电脑上用 admin 登录，他操作完退出登录了，也会导致我 token 强行失效

**Comment by 87789771** [comment]
程序正常部署，如果两个浏览器登录，第二次登录会把第一次登录给顶掉。  你之所以可以同时登录，那是因为启用了 “演示” 模式，在配置文件中配置。 在演示模式下，只要token没过期，或者没有主动退出，下次登录都会 沿用上一个toekn。 这是方便我 “演示地址” 给朋友们看的，否则多个人同时看的话，总是被下一个人给顶掉，比较麻烦。

**Comment by ljnMeow** [comment]
了解，感谢解答
