### ISSUE TITLE
作者你好，请问你的LocalAuthGuard  是如何与 LocalStrategy  链接上的？

### ISSUE THREAD

**Issue by huanlirui** [87789771/meimei-nestjs-admin#4]
AuthGuard('local')  这个 是什么意思 ？local 是 代表的  LocalStrategy  ？感觉有点魔法的感觉。。

**Comment by 87789771** [comment]
你可以把整个 AuthGuard 理解成一个独立的小应用，它内部的鉴权逻辑已经被封装好了，外部只需要做到如何使用就好了, 你可以参考官方文档。https://docs.nestjs.cn/8/security  ， 里面的的demo讲的非常清楚。  如果有疑问你可再问我。

**Comment by 87789771** [comment]
class LocalAuthGuard extends AuthGuard('local') 是为了自己的需求对 守卫 进行的进一步封装。

**Comment by huanlirui** [comment]
> 你可以把整个 AuthGuard 理解成一个独立的小应用，它内部的鉴权逻辑已经被封装好了，外部只需要做到如何使用就好了, 你可以参考官方文档。https://docs.nestjs.cn/8/security ， 里面的的demo讲的非常清楚。 如果有疑问你可再问我。

谢谢大佬！已看到！
![image](https://user-images.githubusercontent.com/40491203/185049238-3ef06457-fae6-45ef-a5df-aca1be5f3d2e.png)

**Comment by 87789771** [comment]
通过类的继承来连接的







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月2日(星期五) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [87789771/meimei-nestjs-admin] 作者你好，请问你的LocalAuthGuard  是如何与 LocalStrategy  链接上的？ (Issue #4)





 
Closed #4 as completed.
