### ISSUE TITLE
数据库地址泄露了！

### ISSUE THREAD

**Issue by ehahaC** [87789771/meimei-nestjs-admin#7]
![image](https://user-images.githubusercontent.com/48951186/195272978-7bf06f1f-1c40-41ae-be1e-5872b3442703.png)
数据库地址泄露了，快改掉

**Comment by 87789771** [comment]
没事。这是测试数据，大家可以随便玩。 。   只要别太乱搞就行了。

**Comment by ehahaC** [comment]
好吧，小心服务器
