### ISSUE TITLE
生产环境的 synchronize 不应该设置为 true

### ISSUE THREAD

**Issue by abigmiu** [87789771/meimei-nestjs-admin#8]
https://github.com/87789771/meimei-nestjs-admin/blob/7683fee2b9803fbfbf96a0f36cbd32fa098a1a28/meimei-admin/src/config/config.production.ts#L25

typeorm 有迁移工具

**Comment by 87789771** [comment]
是的，我代码里也有注释进行提示。 不过typeOrm的迁移工具在nest上不适用，可能我不知道怎么合并用吧。
